# Generated by Django 3.1.1 on 2024-01-25 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_feedback_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
