# Generated by Django 5.0.1 on 2024-02-06 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='description_ar',
            field=models.CharField(default='Short description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='description_en',
            field=models.CharField(default='Short description', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='description_ru',
            field=models.CharField(default='Short description', max_length=500),
            preserve_default=False,
        ),
    ]
