# Generated by Django 5.0.1 on 2024-02-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogs', '0002_catalog_description_ar_catalog_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalog',
            old_name='pdf',
            new_name='pdf_ar',
        ),
        migrations.AddField(
            model_name='catalog',
            name='pdf_en',
            field=models.FileField(default='pdf', upload_to='pdf/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalog',
            name='pdf_ru',
            field=models.FileField(default='pdf', upload_to='pdf/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
