# Generated by Django 3.1.1 on 2024-01-02 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='albums_a_title_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='albums_a_title_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='albums_a_title_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='assignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='buildings_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='complex_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='construction_progress',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='construction_start_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='description_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='developer_a_logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='developer_a_title_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='developer_a_title_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='developer_a_title_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='districts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='eoi_a_eoi_items',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='eoi_a_is_eoi_return',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='for_sale_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='is_sold_out',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_album',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_albums_a_images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_amenities',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_br_prices',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_stocks',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_a_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_a_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_fix',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_additional_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_booking_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_booking_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_construction_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_construction_payments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_construction_percent',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_handover_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_handover_payments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_handover_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_on_post_handover_payments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_repeat_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_period',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_repeat_count',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_post_handover_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_post_handover_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_roi_fix',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_roi_payments_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_roi_percent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_title_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_title_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='payment_plans_a_title_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='planned_completion_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='predicted_completion_at',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_a_currency',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_a_max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_a_min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='price_on_request',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sales_status_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sales_status_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='sales_status_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='service_charge',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='status_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_a_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_a_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='title_a_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='type',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='updated_at',
            field=models.TextField(blank=True, null=True),
        ),
    ]
