# Generated by Django 3.1.1 on 2024-01-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_photo_4'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='offer_type',
            field=models.TextField(default='sell'),
        ),
        migrations.AddField(
            model_name='listing',
            name='source',
            field=models.TextField(default='alnair'),
        ),
    ]
