# Generated by Django 3.1.1 on 2024-01-12 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_auto_20240112_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_amenities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
