# Generated by Django 3.1.1 on 2024-01-12 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_auto_20240112_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='listing_amenities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
