# Generated by Django 3.1.1 on 2024-01-25 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_auto_20240112_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(null=True)),
                ('min_price', models.FloatField(null=True)),
                ('max_price', models.FloatField(null=True)),
                ('min_price_m2', models.FloatField(null=True)),
                ('max_price_m2', models.FloatField(null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('min_area_m2', models.FloatField(null=True)),
                ('max_area_m2', models.FloatField(null=True)),
                ('min_area_ft2', models.FloatField(null=True)),
                ('max_area_ft2', models.FloatField(null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
    ]
