# Generated by Django 3.1.1 on 2024-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0015_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenities',
            name='amenity_svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
