# Generated by Django 3.1.1 on 2024-01-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_amenities_amenity_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='districts',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_districts',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
