# Generated by Django 5.0.1 on 2024-01-29 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0018_districts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Amenities',
            new_name='Amenity',
        ),
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='Prices',
            new_name='Price',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='listing_albums_a_images',
            new_name='listing_albums',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='albums_a_title_a_ar',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='albums_a_title_a_en',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='albums_a_title_a_ru',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_a_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_a_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_ar',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_en',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_a_title_a_ru',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_additional_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_booking_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_booking_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_construction_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_construction_payments_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_construction_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_handover_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_handover_payments_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_handover_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_on_post_handover_payments_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_period',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_handover_a_repeat_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_period',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_period_after_roi_a_repeat_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_post_handover_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_post_handover_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_roi_fix',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_roi_payments_count',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_roi_percent',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_title_a_ar',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_title_a_en',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='payment_plans_a_title_a_ru',
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_payment_plans',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ru', models.TextField(blank=True, null=True)),
                ('title_en', models.TextField(blank=True, null=True)),
                ('title_ar', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.album')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a_ru', models.TextField(blank=True, null=True)),
                ('title_a_en', models.TextField(blank=True, null=True)),
                ('title_a_ar', models.TextField(blank=True, null=True)),
                ('on_booking_percent', models.FloatField(null=True)),
                ('on_booking_fix', models.FloatField(blank=True, null=True)),
                ('on_construction_percent', models.FloatField(null=True)),
                ('on_construction_fix', models.FloatField(blank=True, null=True)),
                ('on_construction_payments_count', models.IntegerField(null=True)),
                ('on_handover_percent', models.FloatField(blank=True, null=True)),
                ('on_handover_fix', models.FloatField(blank=True, null=True)),
                ('on_handover_payments_count', models.IntegerField(null=True)),
                ('post_handover_percent', models.FloatField(blank=True, null=True)),
                ('post_handover_fix', models.FloatField(blank=True, null=True)),
                ('on_post_handover_payments_count', models.IntegerField(null=True)),
                ('additional_percent', models.FloatField(null=True)),
                ('additional_fix', models.FloatField(null=True)),
                ('roi_percent', models.FloatField(blank=True, null=True)),
                ('roi_fix', models.FloatField(blank=True, null=True)),
                ('roi_payments_count', models.IntegerField(null=True)),
                ('currency', models.TextField(blank=True, null=True)),
                ('period_after_handover_a_period', models.TextField(blank=True, null=True)),
                ('period_after_handover_a_count', models.TextField(blank=True, null=True)),
                ('period_after_handover_a_repeat_count', models.TextField(blank=True, null=True)),
                ('period_after_roi_a_period', models.TextField(blank=True, null=True)),
                ('period_after_roi_a_count', models.TextField(blank=True, null=True)),
                ('period_after_roi_a_repeat_count', models.TextField(blank=True, null=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Additional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_a_ru', models.TextField(blank=True, null=True)),
                ('title_a_en', models.TextField(blank=True, null=True)),
                ('title_a_ar', models.TextField(blank=True, null=True)),
                ('percent', models.FloatField(null=True)),
                ('fix', models.FloatField(blank=True, null=True)),
                ('payment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.paymentplan')),
            ],
        ),
    ]
