# Generated by Django 5.0.1 on 2024-01-29 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0019_rename_amenities_amenity_rename_districts_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='special_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price_on_request',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
