# Generated by Django 5.0.1 on 2024-01-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0020_listing_special_price_alter_listing_price_on_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='special_price',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
