# Generated by Django 5.0.1 on 2024-01-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0021_alter_listing_special_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additional',
            old_name='title_a_ar',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='title_a_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='additional',
            old_name='title_a_ru',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_handover_a_count',
            new_name='period_after_handover_count',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_handover_a_period',
            new_name='period_after_handover_period',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_handover_a_repeat_count',
            new_name='period_after_handover_repeat_count',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_roi_a_count',
            new_name='period_after_roi_count',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_roi_a_period',
            new_name='period_after_roi_period',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='period_after_roi_a_repeat_count',
            new_name='period_after_roi_repeat_count',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='title_a_ar',
            new_name='title_ar',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='title_a_en',
            new_name='title_en',
        ),
        migrations.RenameField(
            model_name='paymentplan',
            old_name='title_a_ru',
            new_name='title_ru',
        ),
    ]
