# Generated by Django 5.0.1 on 2024-01-30 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0023_mainalbumimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_fully_loaded',
            field=models.BooleanField(default=False),
        ),
    ]
