# Generated by Django 5.0.1 on 2024-01-31 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0025_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
