# Generated by Django 5.0.1 on 2024-01-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0028_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='key_mode',
            field=models.BooleanField(default=False),
        ),
    ]
