# Generated by Django 5.0.1 on 2024-02-18 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0031_bookmark_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additional',
            name='payment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='listings.paymentplan'),
        ),
        migrations.AlterField(
            model_name='album',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='amenity',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='district',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.album'),
        ),
        migrations.AlterField(
            model_name='mainalbumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_album_images', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='paymentplan',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='listings.listing'),
        ),
        migrations.AlterField(
            model_name='price',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='listings.listing'),
        ),
    ]
