# Generated by Django 5.0.1 on 2024-02-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0033_listing_developer_alter_listing_realtor'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentplan',
            name='alnair_id',
            field=models.IntegerField(null=True),
        ),
    ]
