# Generated by Django 5.0.1 on 2024-02-28 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0034_paymentplan_alnair_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_limited_publication',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
