# Generated by Django 5.0.1 on 2024-02-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0035_listing_is_limited_publication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='complex_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
