# Generated by Django 5.0.1 on 2024-03-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0036_alter_listing_complex_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='special_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
