# Generated by Django 5.0.1 on 2024-03-02 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0038_alter_additional_title_ar_alter_additional_title_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='suitable_for',
            field=models.IntegerField(choices=[(1, '1 guest'), (2, '2 guests'), (3, '3 guests'), (4, 'More than 3 guests')], default=4),
        ),
    ]
