# Generated by Django 5.0.1 on 2024-03-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0039_listing_suitable_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='apartment_type',
            field=models.CharField(choices=[('STUDIO', 'Studio'), ('1BR', '1 Bedroom'), ('2BR', '2 Bedroom'), ('3BR', '3 Bedroom'), ('4BR', '4 Bedroom'), ('4+BR', '4+ Bedroom'), ('MICRO', 'Micro'), ('ALCOVE', 'Alcove'), ('BASEMENT', 'Basement'), ('LOFT', 'Loft'), ('DUPLEX', 'Duplex'), ('PENTHOUSE', 'Penthouse')], default='1BR', max_length=12),
        ),
    ]
