# Generated by Django 5.0.1 on 2024-03-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0040_listing_apartment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='price_min_usd',
            field=models.IntegerField(null=True),
        ),
    ]
