# Generated by Django 5.0.1 on 2024-03-06 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0041_listing_price_min_usd'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='rooms',
            field=models.IntegerField(null=True),
        ),
    ]
