# Generated by Django 5.0.1 on 2024-02-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='create_date',
            new_name='created',
        ),
    ]
