# Generated by Django 5.0.1 on 2024-02-26 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_create_date_reservation_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
