# Generated by Django 5.0.1 on 2024-02-26 13:27

import djmoney.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_alter_reservation_cleaning_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cleaning_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='cleaning_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='UDS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='concierge_service_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='concierge_service_cost_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='UDS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_day',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_day_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='UDS', editable=False, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_month',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_month_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('EUR', 'Euro'), ('RUB', 'Russian Ruble'), ('USD', 'US Dollar'), ('AED', 'United Arab Emirates Dirham')], default='UDS', editable=False, max_length=3, null=True),
        ),
    ]
