# Generated by Django 5.0.1 on 2024-02-26 13:29

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0007_alter_reservation_cleaning_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='cleaning_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='concierge_service_cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_day',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_month',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
