# Generated by Django 5.0.1 on 2024-02-26 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_reservation_cleaning_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='numbers_of_cleanings',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='numbers_of_concierge_services',
            field=models.IntegerField(blank=True, default=2, null=True),
        ),
    ]
