# Generated by Django 5.0.1 on 2024-02-26 13:36

import djmoney.models.fields
import djmoney.models.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0009_alter_reservation_numbers_of_cleanings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='concierge_service_cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_day',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='price_per_month',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='UDS', max_digits=10, null=True, validators=[djmoney.models.validators.MinMoneyValidator(0)]),
        ),
    ]
