# Generated by Django 5.0.1 on 2024-02-14 18:36

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+79216341327', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
