# Generated by Django 5.0.1 on 2024-02-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_profile_phone'),
        ('listings', '0032_alter_additional_payment_plan_alter_album_listing_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bookmarks',
            field=models.ManyToManyField(related_name='bookmarked_by', to='listings.listing'),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='listings.listing'),
        ),
    ]
