# Generated by Django 5.0.1 on 2024-02-06 11:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-fixed', '-time_create'], 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='full_description',
        ),
        migrations.RemoveField(
            model_name='article',
            name='short_description',
        ),
        migrations.AddField(
            model_name='article',
            name='chapter_ar',
            field=models.TextField(default='chapter text', max_length=255, verbose_name='Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='chapter_en',
            field=models.TextField(default='chapter text', max_length=255, verbose_name='Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='chapter_ru',
            field=models.TextField(default='chapter text', max_length=255, verbose_name='Chapter'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_ar',
            field=models.TextField(default='text', verbose_name='Text ar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_en',
            field=models.TextField(default='text', verbose_name='Text en'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='text_ru',
            field=models.TextField(default='text', verbose_name='Text ru'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='author_posts', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='article',
            name='fixed',
            field=models.BooleanField(default=False, verbose_name='Fixed'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('draft', 'Draft')], default='published', max_length=10, verbose_name='Post status'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('png', 'jpg', 'webp', 'jpeg', 'gif'))], verbose_name='Post preview'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='time_update',
            field=models.DateTimeField(auto_now=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ar',
            field=models.CharField(max_length=255, verbose_name='Title ar'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, verbose_name='Title en'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, verbose_name='Title ru'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updater_posts', to=settings.AUTH_USER_MODEL, verbose_name='Updater'),
        ),
    ]
