# Generated by Django 5.0.1 on 2024-02-07 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_article_thumbnail_article_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='chapter_ar',
            new_name='category_ar',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='chapter_en',
            new_name='category_en',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='chapter_ru',
            new_name='category_ru',
        ),
    ]
