# Generated by Django 5.0.1 on 2024-02-07 16:58

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_chapter_ar_article_category_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text_ar',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_en',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='text_ru',
            field=tinymce.models.HTMLField(),
        ),
    ]
