class Listings_listing(models.Model):
    complex_id = models.IntegerField(null=True)
    type = models.TextField(blank=True, null=True)
    logo = models.TextField(blank=True, null=True)
    photo = models.TextField(blank=True, null=True)
    title_a_ru = models.TextField(blank=True, null=True)
    title_a_en = models.TextField(blank=True, null=True)
    title_a_ar = models.TextField(blank=True, null=True)
    description_a_ru = models.TextField(blank=True, null=True)
    description_a_en = models.TextField(blank=True, null=True)
    description_a_ar = models.TextField(blank=True, null=True)
    price_on_request = models.IntegerField(null=True)
    status_a_ru = models.TextField(blank=True, null=True)
    status_a_en = models.TextField(blank=True, null=True)
    status_a_ar = models.TextField(blank=True, null=True)
    construction_start_at = models.TextField(blank=True, null=True)
    construction_progress = models.FloatField(null=True)
    planned_completion_at = models.TextField(blank=True, null=True)
    predicted_completion_at = models.TextField(blank=True, null=True)
    listings_listing_amenities = models.JSONField(blank=True, null=True)
    developer_a_title_a_ru = models.TextField(blank=True, null=True)
    developer_a_title_a_en = models.TextField(blank=True, null=True)
    developer_a_title_a_ar = models.TextField(blank=True, null=True)
    developer_a_logo = models.TextField(blank=True, null=True)
    districts = models.TextField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    latitude = models.FloatField(null=True)
    longitude = models.FloatField(null=True)
    listings_listing_album = models.JSONField(blank=True, null=True)
    listings_listing_albums = models.JSONField(blank=True, null=True)
    buildings_count = models.IntegerField(null=True)
    for_sale_count = models.IntegerField(null=True)
    price_a_min = models.IntegerField(null=True)
    price_a_max = models.IntegerField(null=True)
    price_a_currency = models.TextField(blank=True, null=True)
    listings_listing_br_prices = models.JSONField(blank=True, null=True)
    updated_at = models.TextField(blank=True, null=True)
    is_sold_out = models.IntegerField(null=True)
    payment_plans_a_title_a_ru = models.TextField(blank=True, null=True)
    payment_plans_a_title_a_en = models.TextField(blank=True, null=True)
    payment_plans_a_title_a_ar = models.TextField(blank=True, null=True)
    payment_plans_a_on_booking_percent = models.IntegerField(null=True)
    payment_plans_a_on_booking_fix = models.TextField(blank=True, null=True)
    payment_plans_a_on_construction_percent = models.IntegerField(null=True)
    payment_plans_a_on_construction_fix = models.TextField(blank=True, null=True)
    payment_plans_a_on_construction_payments_count = models.IntegerField(null=True)
    payment_plans_a_on_handover_percent = models.IntegerField(null=True)
    payment_plans_a_on_handover_fix = models.TextField(blank=True, null=True)
    payment_plans_a_on_handover_payments_count = models.IntegerField(null=True)
    payment_plans_a_post_handover_percent = models.TextField(blank=True, null=True)
    payment_plans_a_post_handover_fix = models.TextField(blank=True, null=True)
    payment_plans_a_on_post_handover_payments_count = models.IntegerField(null=True)
    payment_plans_a_additional_a_title_a_ru = models.TextField(blank=True, null=True)
    payment_plans_a_additional_a_title_a_en = models.TextField(blank=True, null=True)
    payment_plans_a_additional_a_title_a_ar = models.TextField(blank=True, null=True)
    payment_plans_a_additional_a_percent = models.IntegerField(null=True)
    payment_plans_a_additional_a_fix = models.TextField(blank=True, null=True)
    payment_plans_a_additional_percent = models.IntegerField(null=True)
    payment_plans_a_additional_fix = models.IntegerField(null=True)
    payment_plans_a_roi_percent = models.TextField(blank=True, null=True)
    payment_plans_a_roi_fix = models.TextField(blank=True, null=True)
    payment_plans_a_roi_payments_count = models.IntegerField(null=True)
    payment_plans_a_currency = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_handover_a_period = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_handover_a_count = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_handover_a_repeat_count = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_roi_a_period = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_roi_a_count = models.TextField(blank=True, null=True)
    payment_plans_a_period_after_roi_a_repeat_count = models.TextField(blank=True, null=True)
    sales_status_a_ru = models.TextField(blank=True, null=True)
    sales_status_a_en = models.TextField(blank=True, null=True)
    sales_status_a_ar = models.TextField(blank=True, null=True)
    listings_listing_stocks = models.JSONField(blank=True, null=True)
    eoi_a_is_eoi_return = models.TextField(blank=True, null=True)
    eoi_a_eoi_items = models.TextField(blank=True, null=True)
    service_charge = models.TextField(blank=True, null=True)
    assignment = models.TextField(blank=True, null=True)

