# Generated by Django 5.0.1 on 2024-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realtor',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='realtor',
            name='name_en',
            field=models.CharField(default='Input name here', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='name_ru',
            field=models.CharField(default='Input name here', max_length=200),
            preserve_default=False,
        ),
    ]
