# Generated by Django 5.0.1 on 2024-02-15 15:29

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_rename_name_realtor_name_ar_realtor_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='description',
        ),
        migrations.AddField(
            model_name='realtor',
            name='description_ar',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='description_en',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='description_ru',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='experience_ar',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='experience_en',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='experience_ru',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='job_title_ar',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='job_title_en',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='job_title_ru',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='language_ar',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='language_en',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='language_ru',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='specialization_ar',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='specialization_en',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='specialization_ru',
            field=tinymce.models.HTMLField(default='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='realtor',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
