# Generated by Django 5.0.1 on 2024-02-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0003_remove_realtor_description_realtor_description_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realtor',
            name='experience_ar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='experience_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='experience_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='job_title_ar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='job_title_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='job_title_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='language_ar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='language_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='language_ru',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='specialization_ar',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='specialization_en',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='realtor',
            name='specialization_ru',
            field=models.CharField(max_length=200),
        ),
    ]
