# Generated by Django 5.0.1 on 2024-02-23 13:05

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0032_alter_additional_payment_plan_alter_album_listing_and_more'),
        ('realtors', '0004_alter_realtor_experience_ar_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('developer_a_title_a_ru', models.TextField(blank=True, null=True)),
                ('developer_a_title_a_en', models.TextField(blank=True, null=True)),
                ('developer_a_title_a_ar', models.TextField(blank=True, null=True)),
                ('developer_a_logo', models.TextField(blank=True, null=True)),
                ('year_of_foundation', models.TextField(blank=True, max_length=4, null=True)),
                ('buildings_finished', models.IntegerField(blank=True, null=True)),
                ('complexes_finished', models.IntegerField(blank=True, null=True)),
                ('buildings_in_progress', models.IntegerField(blank=True, null=True)),
                ('complexes_in_progress', models.IntegerField(blank=True, null=True)),
                ('main_office', models.TextField(blank=True, null=True)),
                ('number_of_employees', models.IntegerField(blank=True, null=True)),
                ('stock_valuation', models.IntegerField(blank=True, null=True)),
                ('text_en', tinymce.models.HTMLField()),
                ('text_ru', tinymce.models.HTMLField()),
                ('text_ar', tinymce.models.HTMLField()),
                ('listings', models.ManyToManyField(related_name='listed_by', to='listings.listing')),
                ('realtor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='realtors.realtor')),
            ],
            options={
                'verbose_name': 'Developer',
                'verbose_name_plural': 'Developers',
                'db_table': 'developers',
                'ordering': ['-id'],
            },
        ),
    ]
