# Generated by Django 5.0.1 on 2024-02-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0002_alter_developer_listings'),
    ]

    operations = [
        migrations.AddField(
            model_name='developer',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
