# Generated by Django 5.0.1 on 2024-02-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0003_developer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_a_logo',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_a_title_a_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_a_title_a_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='developer_a_title_a_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='year_of_foundation',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
