# Generated by Django 5.0.1 on 2024-02-24 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0005_rename_developer_a_logo_developer_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='slug',
            field=models.SlugField(max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
