# Generated by Django 5.0.1 on 2024-02-24 15:35

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0006_alter_developer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='text_ar',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='text_en',
            field=tinymce.models.HTMLField(blank=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='text_ru',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
