# Generated by Django 5.0.1 on 2024-02-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developers', '0007_alter_developer_text_ar_alter_developer_text_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='title_ar',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='developer',
            name='title_ru',
            field=models.CharField(max_length=255),
        ),
    ]
